### ISSUE TITLE
UML-Diagram

### ISSUE THREAD

**Issue by nicoschurig** [tuning-8/swe-sose2022_exam-repository#1]
![classstructure_swe_exam](https://user-images.githubusercontent.com/93139988/177791097-0d9545eb-959a-40aa-89c7-ef6f94ef94d0.png)

- This is an unfinished version of the UML-Diagram, that is not ready to being used for the project!
- It is just a concept, what the final diagram should contain, referring to our current state of knowledge.
- Still there will be changes and enhancements for this diagram.

**Comment by nicoschurig** [comment]
![classstructure_swe_exam](https://user-images.githubusercontent.com/93139988/179751950-9f468702-a7ed-417b-acf7-7df41ad9b96e.png)

- This is the UML-Diagram referring to our current state of knowledge.
- The TxtReader class may be added to the UML-Diagram.
- Each class can now be implemented referring to the diagram.
- Still there will probably be changes to the UML-Diagram!

**Comment by nicoschurig** [comment]
![classstructure_swe_exam](https://user-images.githubusercontent.com/93139988/179952668-935b0fa5-2160-4d1e-b0d7-f41fefc2f55e.png)

- The _IngredientsTranslator_ class was added to the UML-Diagram.
- This class is needed to translate the ingredient indicators in the _specialIngredients_ List of the _Dish_ class.
- The _TranslateIngredientIndicator_ methods are expected to be called within the _WriteMenuInformation_ method of the _XmlWriter_ class.
- Still there might be changes to the diagram soon.

**Comment by nicoschurig** [comment]
- There have to be changes made to the UML-Diagram!
- The website of the student administration Freiberg provides the price data in string format.
- Change the _Prices_ array in _Dish_ class from double to string.
- The prices will be formatted within the _XmlWriter_ class(#6 ).
- Add a _removedCharacters_ array to the _XmlWriter_ class.

**Comment by nicoschurig** [comment]
![classstructure_swe_exam](https://user-images.githubusercontent.com/93139988/180380076-bab90284-76bf-40b3-ae58-4387f3ae2c12.png)

- Added the changes mentioned above into the UMLDiagram!

**Comment by nicoschurig** [comment]
![classstructure_swe_exam](https://user-images.githubusercontent.com/93139988/180940632-3fa863b2-cb3c-4ce4-bc93-adcec7f523ef.png)

- Changed the fields in _XmlWriter_ class to private readonly.
- Edited the HtmlParser class to match Capitalization Conventions.
- Changed the datatype of _specialIngredients_ list in _Dish_ class.
- Changed the first parameter of _WritePriceInformation()_ method to _Dish dish_.
- Implemented some access modifier changes in the classes: _Menu_, _Weekday_, _Category_ and _Dish_.

**Comment by tuning-8** [comment]
- please mark the 'IngredientsTranslator' class and its members as static

**Comment by nicoschurig** [comment]
![classstructure_swe_exam](https://user-images.githubusercontent.com/93139988/180949014-23d0cea6-c43c-454c-9058-ca1f5302485e.png)

- Implemented the changes requested.
